name: sync-gpustack-dev-images-daily

on:
  schedule:
    - cron: "45 */4 * * *"
  workflow_dispatch:

jobs:
  sync-gpustack:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Pull gpustack/gpustack:dev
        run: docker pull gpustack/gpustack:dev

      - name: Run gpustack copy-images
        run: |
          docker run --rm --entrypoint "" gpustack/gpustack:dev gpustack copy-images \
            --repository gpustack \
            --dest ${{ vars.DOCKER_MIRROR_REGISTRY }} \
            --dest-user ${{ secrets.DOCKER_MIRROR_USER }} \
            --dest-passwd ${{ secrets.DOCKER_MIRROR_PASSWORD }}
